---
title: "MELNHE Fall Error Checking Graphs"
format: 
  pptx:
    fig-width: 13
    fig-height: 8.5
editor: visual
---


```{r}
#| include: false
#| message: false
#| warning: false


#Install packages:
library(ggplot2)
library(tidyr)
library(gridExtra)
library(RColorBrewer)

# FALL GRAPHS

#Import data
lit.all2 <- read.csv(here::here("data","MELNHE Litterfall EDI Data - December.csv"))



table(lit.all2$Stand, lit.all2$Lityear)

#Isolate fall data
lit.fall.sort2<-subset(lit.all2, Season == "Fall" & Sorted == "Y")


lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & lit.fall.sort2$Stand == "C2" &
               lit.fall.sort2$Plot=="2" & lit.fall.sort2$Basket=="2",] <- "A3"
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & lit.fall.sort2$Stand == "C2" &
               lit.fall.sort2$Plot=="2" & lit.fall.sort2$Basket=="5",] <- "A1"

lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "C2" & lit.fall.sort2$Plot=="2" 
               & lit.fall.sort2$Basket=="2",] <- "A3"

lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "C2" & lit.fall.sort2$Plot=="2" 
               & lit.fall.sort2$Basket=="5",] <- "A1"

#### C4 plot 3

lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "C4" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="3",] <- "A3"
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "C4" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="4",] <- "B2"

lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "C4" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="3",] <- "A3"

lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "C4" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="4",] <- "B2"


## HBM 2
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="2" 
               & lit.fall.sort2$Basket=="1",] <- "A1"
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="2" 
               & lit.fall.sort2$Basket=="3",] <- "B2"

lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="2" 
               & lit.fall.sort2$Basket=="1",] <- "A1"
lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="2" 
               & lit.fall.sort2$Basket=="3",] <- "B2"

## HBM 3

lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="2",] <- "A1"
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="3",] <- "A2"
lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="2",] <- "A1"
lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="3",] <- "A2"

## HBM 4
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="A1",] <- "1"
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="CENTER",] <- "5"

lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="A1",] <- "1"
lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "HBM" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="CENTER",] <- "5"

## HBO 1
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "HBO" & lit.fall.sort2$Plot=="1" 
               & lit.fall.sort2$Basket=="A3",] <- "4"
lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "HBO" & lit.fall.sort2$Plot=="1" 
               & lit.fall.sort2$Basket=="A3",] <- "4"

## HBO 3
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "HBO" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="2",] <- "C1"
lit.fall.sort2[lit.fall.sort2$Lityear=="2010" & 
                 lit.fall.sort2$Stand == "HBO" & lit.fall.sort2$Plot=="3" 
               & lit.fall.sort2$Basket=="2",] <- "C1"


## test specific years baskets
lit.fall.sort2[lit.fall.sort2$Lityear=="2009" & 
                 lit.fall.sort2$Stand == "HBO" & lit.fall.sort2$Plot=="3",]

 
names(lit.fall.sort2)
#Convert to long form
lgf2<- gather(lit.fall.sort2[,c(1:35)], "SP","mass",c(14:35))
lgf2$staplo<-paste(lgf2$Stand, lgf2$Plot)
lgf2$Year<-as.factor(lgf2$Year)
lgf2$mass<-as.numeric(lgf2$mass)



# deal with species

lgf2[lgf2$SP== "PRSE2", "SP"] <- "PRPE2"
lgf2[lgf2$SP== "PIRU", "SP"] <- "TSCA"
lgf2[lgf2$SP== "BEPO", "SP"] <- "BEPA"
lgf2[lgf2$SP== "POGR4", "SP"] <- "PO_sp"
lgf2[lgf2$SP== "POTR5", "SP"] <- "PO_sp"
lgf2[lgf2$SP== "BE_sp", "SP"] <- "BEPA"


lgf2[lgf2$SP== "TSCA", "SP"] <- "Unknown"

uncommon_sp <- c("ACSP2","ACPE", "FRAM2","QURU","SOAM3","TIAM","PO_sp")


common_sp <- c("BEAL2","BEPA", "FAGR2","PRPE2","ACRU","ACSA3","VILA11")


lgf2[lgf2$SP %in% common_sp , "Common"] <- "Major species"

lgf2 <- lgf2[ , c("Lityear","Site","Stand","Plot","Basket","Basket_Area",
                  "SP","mass","staplo")]

# unsorted <- subset(lit.all2, Season == "Fall" & Sorted == "N")
# unsorted$SP <- "total mass"
# unsorted$staplo <- paste(unsorted$Stand, unsorted$Plot)
# unsorted$mass <- as.numeric( unsorted$Total_Mass)
# unsorted <- unsorted[ , c("Lityear","Site","Stand","Plot","Basket","Basket_Area",
#                   "SP","mass","staplo")]

str(lgf2)
#lgf2 <- rbind(unsorted, lgf2)

lgf2$Year <- as.factor(lgf2$Lityear)


#Pick a color palette
#install.packages("pals")
library(pals)

n <- length(unique(lgf2$SP))
litcol <- as.character(pals::polychrome(n))

lgf2$og_basket <- lgf2$Basket

#streamline the basket labels so that there are only five
lgf2[lgf2$Basket==1, "Basket"] <- "A1"
lgf2[lgf2$Basket==2, "Basket"] <- "A3"
lgf2[lgf2$Basket==3, "Basket"] <- "B2"
lgf2[lgf2$Basket==4, "Basket"] <- "C1"
lgf2[lgf2$Basket==5, "Basket"] <- "C3"

lgf2[lgf2$Basket=="LF1", "Basket"] <- "1"
lgf2[lgf2$Basket=="LF2", "Basket"] <- "2"
lgf2[lgf2$Basket=="LF3", "Basket"] <- "3"
lgf2[lgf2$Basket=="LF4", "Basket"] <- "4"
lgf2[lgf2$Basket=="LF5", "Basket"] <- "5"


###################

# to identify the negatives
# negatives <- lgf2[lgf2$mass<0,]
# negatives$basket_id <- paste(negatives$Lityear, negatives$staplo, negatives$og_basket)
# negatives <- negatives[!is.na(negatives$mass),]
# negatives <- negatives[order(negatives$mass),]
# head(negatives)
# unique(negatives$basket_id)
# 
# write.csv(negatives[ , c("Lityear","Stand","Plot","og_basket","SP","mass","basket_id"),],
#           file= "Negative basket masses.csv")

##########################################
# Bartlett baskets
BART <- lgf2[lgf2$Site=="BEF",]

BART[BART$Basket=="A1", "Basket"] <- "1"
BART[BART$Basket=="A3", "Basket"] <- "2"
BART[BART$Basket=="B2", "Basket"] <- "3"
BART[BART$Basket=="C1", "Basket"] <- "4"
BART[BART$Basket=="C3", "Basket"] <- "5"

table(BART$Stand, BART$Basket)

##########################################
# HB baskets
HBM <- lgf2[lgf2$Stand== "HBM",]

table(HBM$Lityear, HBM$Basket)
HBM[HBM$Basket=="A1", "Basket"] <- "1"
HBM[HBM$Basket=="A2", "Basket"] <- "2"
HBM[HBM$Basket=="CENTER", "Basket"] <- "3"
HBM[HBM$Basket=="B1", "Basket"] <- "4"
HBM[HBM$Basket=="B2", "Basket"] <- "5"
table(HBM$Lityear, HBM$Basket)

#############
HBO <- lgf2[lgf2$Stand=="HBO",]


table(HBO$Lityear, HBO$Basket)
HBO[HBO$Basket=="Y3", "Basket"] <- "5"

HBO[HBO$Basket=="A1", "Basket"] <- "1"
HBO[HBO$Basket=="A3", "Basket"] <- "2"
HBO[HBO$Basket=="B1", "Basket"] <- "3"
HBO[HBO$Basket=="B2", "Basket"] <- "3"
HBO[HBO$Basket=="C1", "Basket"] <- "4"
HBO[HBO$Basket=="C3", "Basket"] <- "5"

table(HBO$Lityear, HBO$Basket)


##########################################
# JB baskets
JBM <- lgf2[lgf2$Stand=="JBM",]
table(JBM$Lityear, JBM$Basket)
JBM[JBM$Basket=="A1", "Basket"] <- "1"
JBM[JBM$Basket=="A2", "Basket"] <- "2"
JBM[JBM$Basket=="CENTER", "Basket"] <- "3"
JBM[JBM$Basket=="B1", "Basket"] <- "4"
JBM[JBM$Basket=="B2", "Basket"] <- "5"

table(JBM$Lityear, JBM$Basket)


JBO <- lgf2[lgf2$Stand=="JBO",]
table(JBO$Lityear, JBO$Basket)

JBO[JBO$Basket=="A1", "Basket"] <- "1"
JBO[JBO$Basket=="A3", "Basket"] <- "2"
JBO[JBO$Basket=="B2", "Basket"] <- "3"
JBO[JBO$Basket=="C1", "Basket"] <- "4"
JBO[JBO$Basket=="C3", "Basket"] <- "5"
table(JBO$Lityear, JBO$Basket)


# BART$Year <- as.numeric(BART$Year)
# BART$Year <- factor(BART$Year, levels = sort(unique(as.numeric(as.character(BART$Year)))))
# BART$Year <- factor(BART$Year, levels = sort(unique(as.numeric(as.character(BART$Year)))))
# BART$Year <- factor(BART$Year, levels = sort(unique(as.numeric(as.character(BART$Year)))))
# BART$Year <- factor(BART$Year, levels = sort(unique(as.numeric(as.character(BART$Year)))))



```

------------------------------------------------------------------------
```{r}
# SubsetR
df_sub <-BART[BART$staplo == "C1 1",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) +
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C1 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept =  c(2.5, 4.5), linetype = "dashed", color = "red", linewidth = 1)
```


```{r}

# Subset
df_sub <-BART[BART$staplo == "C1 2",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub[df_sub$SP!="total mass",], aes(x = Year, y = mass, fill = SP)) +
  geom_point(data=df_sub[df_sub$SP=="total mass",], aes(x = Year, y = mass))+
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C1 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept =  c(2.5, 4.5), linetype = "dashed", color = "red", linewidth = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C1 3",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub[df_sub$SP!="total mass",], aes(x = Year, y = mass, fill = SP)) +
  geom_point(data=df_sub[df_sub$SP=="total mass",], aes(x = Year, y = mass))+
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C1 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept =  c(2.5, 4.5), linetype = "dashed", color = "red", linewidth = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C1 4",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub[df_sub$SP!="total mass",], aes(x = Year, y = mass, fill = SP)) +
  geom_point(data=df_sub[df_sub$SP=="total mass",], aes(x = Year, y = mass))+
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C1 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept =  c(2.5, 4.5), linetype = "dashed", color = "red", linewidth = 1)
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <-BART[BART$staplo == "C2 1",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C2 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C2 2",]



# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C2 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C2 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C2 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C2 4",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C2 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <-BART[BART$staplo == "C3 1",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C3 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C3 2",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C3 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C3 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C3 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C3 4",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C3 4 over the years")
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <-BART[BART$staplo == "C4 1",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C4 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C4 2",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C4 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C4 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C4 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C4 4",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C4 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <-BART[BART$staplo == "C5 1",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C5 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C5 2",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C5 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C5 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C5 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C5 4",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C5 4 over the years")
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <-BART[BART$staplo == "C6 1",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C6 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C6 2",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C6 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C6 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C6 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C6 4",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C6 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <-BART[BART$staplo == "C7 1",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C7 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C7 2",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C7 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C7 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C7 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C7 4",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C7 4 over the years")+
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <-BART[BART$staplo == "C8 1",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C8 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C8 2",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C8 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C8 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C8 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C8 4",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C8 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <-BART[BART$staplo == "C9 1",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C9 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C9 2",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C9 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C9 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C9 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <-BART[BART$staplo == "C9 4",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand C9 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <- HBM[HBM$staplo == "HBM 1",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand HBM 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- HBM[HBM$staplo == "HBM 2",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand HBM 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- HBM[HBM$staplo == "HBM 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand HBM 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- HBM[HBM$staplo == "HBM 4",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand HBM 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <- HBO[HBO$staplo == "HBO 1",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand HBO 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- HBO[HBO$staplo == "HBO 2",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand HBO 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- HBO[HBO$staplo == "HBO 3",]

# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand HBO 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- HBO[HBO$staplo == "HBO 4",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand HBO 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}


# Subset
df_sub <- JBM[JBM$staplo == "JBM 1",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand JBM 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- JBM[JBM$staplo == "JBM 2",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand JBM 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- JBM[JBM$staplo == "JBM 3",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand JBM 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- JBM[JBM$staplo == "JBM 4",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand JBM 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}

# Subset
df_sub <- JBO[JBO$staplo == "JBO 1",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand JBO 1 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- JBO[JBO$staplo == "JBO 2",]



# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand JBO 2 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- JBO[JBO$staplo == "JBO 3",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand JBO 3 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(3.5), linetype = "dashed", color = "red", size = 1)
```

------------------------------------------------------------------------

```{r}
# Subset
df_sub <- JBO[JBO$staplo == "JBO 4",]


# Create plot
#baskets may not correspond with other baskets in the same panel across red dotted line
ggplot(df_sub, aes(x = Year, y = mass, fill = SP)) + 
  geom_bar(stat = "identity", col = "black") + 
  theme_bw() +
  facet_wrap(~Basket, scales = "fixed", nrow = 2) +
  scale_fill_manual(values = litcol[1:length(unique(df_sub$SP))]) +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) +
  ggtitle("Stand JBO 4 over the years") +
  # Add vertical separator lines BETWEEN certain years
  geom_vline(xintercept = c(2.5, 4.5), linetype = "dashed", color = "red", linewidth = 1)
```
